/**
 * Local copy of shared tool constants to avoid cross-package import issues in dev
 */

export const TOOL_CATEGORIES = {
  TEXT_TOOLS: 'Text Tools',
  DOCUMENT_TOOLS: 'Document Tools',
  DEVELOPER_TOOLS: 'Developer Tools',
  DESIGN_TOOLS: 'Design Tools',
  SECURITY_TOOLS: 'Security Tools',
  IMAGE_TOOLS: 'Image Tools',
  CONVERSION_TOOLS: 'Conversion Tools',
  FILE_TOOLS: 'File Tools',
  WEB_TOOLS: 'Web Tools',
  CALCULATOR_TOOLS: 'Calculator Tools'
};

export const tools = [
  // HIGHEST PRIORITY - Most searched and used tools
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure, random passwords with customizable length and character sets.',
    path: '/tools/password-generator',
    category: 'security',
    keywords: ['password', 'generate', 'secure', 'random', 'security', 'strong password'],
    icon: '🔐',
    featured: true,
    priority: 0.9,
    built: true,
  },
  {
    id: 'base64',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode text to Base64 or decode Base64 back to text. Useful for encoding binary data or simple text obfuscation.',
    path: '/tools/base64',
    category: 'encoding',
    keywords: ['base64', 'encode', 'decode', 'text', 'binary', 'encoding'],
    icon: '🔤',
    featured: true,
    priority: 0.9,
    built: true,
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format and validate JSON data with proper indentation and syntax highlighting.',
    path: '/tools/json-formatter',
    category: 'developer',
    keywords: ['json', 'format', 'validate', 'developer', 'code', 'beautify'],
    icon: '📋',
    featured: true,
    priority: 0.8,
    built: true,
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode or decode URLs to handle special characters and ensure proper web compatibility.',
    path: '/tools/url-encoder',
    category: 'encoding',
    keywords: ['url', 'encode', 'decode', 'web', 'link', 'percent encoding'],
    icon: '🔗',
    featured: true,
    priority: 0.8,
    built: true,
  },
  {
    id: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes for URLs, text, or contact information.',
    path: '/tools/qr-code-generator',
    category: 'conversion',
    keywords: ['qr code', 'generate', 'barcode', 'mobile', 'scan', 'quick response'],
    icon: '📱',
    featured: true,
    priority: 0.8,
    built: true,
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress images to reduce file size while maintaining quality.',
    path: '/tools/image-compressor',
    category: 'image',
    keywords: ['image', 'compress', 'optimize', 'file size', 'quality', 'jpg', 'png'],
    icon: '🖼️',
    featured: true,
    priority: 0.8,
    built: false,
  },
  {
    id: 'pdf-merger',
    name: 'PDF Merger',
    description: 'Combine multiple PDF files into a single document. Upload your PDFs and merge them easily.',
    path: '/tools/pdf-merger',
    category: 'document',
    keywords: ['pdf', 'merge', 'combine', 'document', 'files'],
    icon: '📄',
    featured: true,
    priority: 0.7,
    built: false,
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert between different color formats: HEX, RGB, HSL, and more.',
    path: '/tools/color-converter',
    category: 'design',
    keywords: ['color', 'convert', 'hex', 'rgb', 'hsl', 'design', 'picker'],
    icon: '🎨',
    featured: true,
    priority: 0.7,
    built: false,
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate various hash values (MD5, SHA1, SHA256) for text or files.',
    path: '/tools/hash-generator',
    category: 'security',
    keywords: ['hash', 'md5', 'sha1', 'sha256', 'generate', 'security', 'checksum'],
    icon: '🔒',
    featured: true,
    priority: 0.7,
    built: true,
  },
  {
    id: 'text-case-converter',
    name: 'Text Case Converter',
    description: 'Convert text between different cases: UPPERCASE, lowercase, Title Case, and more.',
    path: '/tools/text-case-converter',
    category: 'text',
    keywords: ['text', 'case', 'convert', 'uppercase', 'lowercase', 'title', 'capitalize'],
    icon: '🔤',
    featured: false,
    priority: 0.6,
    built: true,
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON Converter',
    description: 'Convert CSV data to JSON format and vice versa.',
    path: '/tools/csv-to-json',
    category: 'conversion',
    keywords: ['csv', 'json', 'convert', 'data', 'format', 'excel'],
    icon: '📊',
    featured: false,
    priority: 0.6,
    built: true,
  },
  {
    id: 'markdown-editor',
    name: 'Markdown Editor',
    description: 'Write and preview Markdown content with real-time rendering.',
    path: '/tools/markdown-editor',
    category: 'developer',
    keywords: ['markdown', 'editor', 'write', 'preview', 'text', 'github'],
    icon: '✍️',
    featured: false,
    priority: 0.6,
    built: false,
  },
  // ADDITIONAL HIGH-DEMAND TOOLS
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate unique identifiers (UUIDs) for databases, APIs, and applications.',
    path: '/tools/uuid-generator',
    category: 'developer',
    keywords: ['uuid', 'guid', 'generate', 'unique', 'identifier', 'database'],
    icon: '🆔',
    featured: false,
    priority: 0.6,
    built: true,
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and verify JSON Web Tokens to view their payload and headers.',
    path: '/tools/jwt-decoder',
    category: 'developer',
    keywords: ['jwt', 'token', 'decode', 'verify', 'json web token', 'authentication'],
    icon: '🎫',
    featured: false,
    priority: 0.6,
    built: true,
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions with real-time matching and highlighting.',
    path: '/tools/regex-tester',
    category: 'developer',
    keywords: ['regex', 'regular expression', 'test', 'pattern', 'match', 'debug'],
    icon: '🔍',
    featured: false,
    priority: 0.6,
    built: true,
  },
  {
    id: 'text-diff',
    name: 'Text Diff Checker',
    description: 'Compare two texts and highlight the differences between them.',
    path: '/tools/text-diff',
    category: 'text',
    keywords: ['diff', 'compare', 'text', 'difference', 'merge', 'version control'],
    icon: '📝',
    featured: false,
    priority: 0.5,
    built: true,
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, and paragraphs in your text.',
    path: '/tools/word-counter',
    category: 'text',
    keywords: ['word count', 'character count', 'text analysis', 'writing', 'essay'],
    icon: '📊',
    featured: false,
    priority: 0.5,
    built: true,
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates.',
    path: '/tools/timestamp-converter',
    category: 'conversion',
    keywords: ['timestamp', 'unix', 'date', 'time', 'convert', 'epoch'],
    icon: '⏰',
    featured: false,
    priority: 0.5,
    built: true,
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text for design mockups and content testing.',
    path: '/tools/lorem-ipsum',
    category: 'text',
    keywords: ['lorem ipsum', 'placeholder', 'text', 'generate', 'mockup', 'design'],
    icon: '📄',
    featured: false,
    priority: 0.5,
    built: true,
  },
  {
    id: 'html-encoder',
    name: 'HTML Encoder/Decoder',
    description: 'Encode or decode HTML entities and special characters.',
    path: '/tools/html-encoder',
    category: 'web',
    keywords: ['html', 'encode', 'decode', 'entities', 'special characters', 'web'],
    icon: '🌐',
    featured: false,
    priority: 0.5,
    built: true,
  },
  {
    id: 'file-size-converter',
    name: 'File Size Converter',
    description: 'Convert between different file size units (KB, MB, GB, TB).',
    path: '/tools/file-size-converter',
    category: 'conversion',
    keywords: ['file size', 'convert', 'kb', 'mb', 'gb', 'tb', 'bytes'],
    icon: '💾',
    featured: false,
    priority: 0.5,
    built: true,
  },
  {
    id: 'number-base-converter',
    name: 'Number Base Converter',
    description: 'Convert numbers between different bases (binary, decimal, hexadecimal, octal).',
    path: '/tools/number-base-converter',
    category: 'conversion',
    keywords: ['number', 'base', 'convert', 'binary', 'hex', 'decimal', 'octal'],
    icon: '🔢',
    featured: false,
    priority: 0.5,
    built: true,
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    description: 'Minify CSS code to reduce file size and improve loading speed.',
    path: '/tools/css-minifier',
    category: 'developer',
    keywords: ['css', 'minify', 'compress', 'optimize', 'web', 'performance'],
    icon: '🎨',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'js-minifier',
    name: 'JavaScript Minifier',
    description: 'Minify JavaScript code to reduce file size and improve loading speed.',
    path: '/tools/js-minifier',
    category: 'developer',
    keywords: ['javascript', 'js', 'minify', 'compress', 'optimize', 'web'],
    icon: '⚡',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description: 'Format and validate XML documents with proper indentation.',
    path: '/tools/xml-formatter',
    category: 'developer',
    keywords: ['xml', 'format', 'validate', 'beautify', 'indent', 'document'],
    icon: '📋',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format SQL queries with proper indentation and syntax highlighting.',
    path: '/tools/sql-formatter',
    category: 'developer',
    keywords: ['sql', 'format', 'query', 'database', 'beautify', 'indent'],
    icon: '🗄️',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'email-validator',
    name: 'Email Validator',
    description: 'Validate email addresses and check their format and deliverability.',
    path: '/tools/email-validator',
    category: 'web',
    keywords: ['email', 'validate', 'check', 'format', 'deliverability', 'spam'],
    icon: '📧',
    featured: false,
    priority: 0.5,
    built: true,
  },
  {
    id: 'ip-lookup',
    name: 'IP Address Lookup',
    description: 'Get detailed information about IP addresses including location and ISP.',
    path: '/tools/ip-lookup',
    category: 'web',
    keywords: ['ip', 'address', 'lookup', 'location', 'isp', 'geolocation'],
    icon: '🌍',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'dns-lookup',
    name: 'DNS Lookup',
    description: 'Perform DNS lookups to find IP addresses, MX records, and other DNS information.',
    path: '/tools/dns-lookup',
    category: 'web',
    keywords: ['dns', 'lookup', 'domain', 'ip', 'mx', 'records', 'resolve'],
    icon: '🔍',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'ssl-checker',
    name: 'SSL Certificate Checker',
    description: 'Check SSL certificate validity, expiration, and security details.',
    path: '/tools/ssl-checker',
    category: 'security',
    keywords: ['ssl', 'certificate', 'check', 'security', 'https', 'expiration'],
    icon: '🔒',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'website-speed-test',
    name: 'Website Speed Test',
    description: 'Test website loading speed and performance metrics.',
    path: '/tools/website-speed-test',
    category: 'web',
    keywords: ['speed', 'test', 'website', 'performance', 'loading', 'page speed'],
    icon: '⚡',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate SEO-friendly meta tags for your website.',
    path: '/tools/meta-tag-generator',
    category: 'web',
    keywords: ['meta', 'tags', 'seo', 'generate', 'website', 'social media'],
    icon: '🏷️',
    featured: false,
    priority: 0.5,
    built: true,
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Generate favicons for your website in multiple sizes and formats.',
    path: '/tools/favicon-generator',
    category: 'web',
    keywords: ['favicon', 'generate', 'website', 'icon', 'browser', 'tab'],
    icon: '🎯',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'sitemap-generator',
    name: 'Sitemap Generator',
    description: 'Generate XML sitemaps for better search engine indexing.',
    path: '/tools/sitemap-generator',
    category: 'web',
    keywords: ['sitemap', 'xml', 'generate', 'seo', 'search engine', 'indexing'],
    icon: '🗺️',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'robots-txt-generator',
    name: 'Robots.txt Generator',
    description: 'Generate robots.txt files to control search engine crawling.',
    path: '/tools/robots-txt-generator',
    category: 'web',
    keywords: ['robots.txt', 'generate', 'seo', 'crawling', 'search engine'],
    icon: '🤖',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'htaccess-generator',
    name: '.htaccess Generator',
    description: 'Generate .htaccess files for Apache server configuration.',
    path: '/tools/htaccess-generator',
    category: 'web',
    keywords: ['htaccess', 'apache', 'server', 'configuration', 'redirect', 'rewrite'],
    icon: '⚙️',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'cron-job-generator',
    name: 'Cron Job Generator',
    description: 'Generate cron job expressions for task scheduling.',
    path: '/tools/cron-job-generator',
    category: 'developer',
    keywords: ['cron', 'job', 'schedule', 'task', 'expression', 'linux'],
    icon: '⏰',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'gitignore-generator',
    name: '.gitignore Generator',
    description: 'Generate .gitignore files for various programming languages and frameworks.',
    path: '/tools/gitignore-generator',
    category: 'developer',
    keywords: ['gitignore', 'git', 'ignore', 'files', 'repository', 'version control'],
    icon: '📁',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'dockerfile-generator',
    name: 'Dockerfile Generator',
    description: 'Generate Dockerfile templates for containerizing applications.',
    path: '/tools/dockerfile-generator',
    category: 'developer',
    keywords: ['dockerfile', 'docker', 'container', 'generate', 'template'],
    icon: '🐳',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'api-doc-generator',
    name: 'API Documentation Generator',
    description: 'Generate API documentation from OpenAPI/Swagger specifications.',
    path: '/tools/api-doc-generator',
    category: 'developer',
    keywords: ['api', 'documentation', 'generate', 'openapi', 'swagger', 'docs'],
    icon: '📚',
    featured: false,
    priority: 0.5,
    built: false,
  },
  // ADVANCED CALCULATORS & MATHEMATICAL TOOLS
  {
    id: 'scientific-calculator',
    name: 'Scientific Calculator',
    description: 'Advanced calculator with trigonometric, logarithmic, and statistical functions.',
    path: '/tools/scientific-calculator',
    category: 'calculator',
    keywords: ['calculator', 'scientific', 'math', 'trigonometry', 'logarithm', 'statistics'],
    icon: '🧮',
    featured: true,
    priority: 0.8,
    built: false,
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate percentages, percentage changes, and percentage-based problems.',
    path: '/tools/percentage-calculator',
    category: 'calculator',
    keywords: ['percentage', 'calculate', 'percent', 'change', 'increase', 'decrease'],
    icon: '💯',
    featured: false,
    priority: 0.6,
    built: true,
  },
  {
    id: 'mortgage-calculator',
    name: 'Mortgage Calculator',
    description: 'Calculate mortgage payments, interest, and amortization schedules.',
    path: '/tools/mortgage-calculator',
    category: 'calculator',
    keywords: ['mortgage', 'loan', 'payment', 'interest', 'amortization', 'finance'],
    icon: '🏠',
    featured: true,
    priority: 0.7,
    built: false,
  },
  {
    id: 'compound-interest-calculator',
    name: 'Compound Interest Calculator',
    description: 'Calculate compound interest, future value, and investment growth.',
    path: '/tools/compound-interest-calculator',
    category: 'calculator',
    keywords: ['compound interest', 'investment', 'finance', 'growth', 'future value'],
    icon: '💰',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'tip-calculator',
    name: 'Tip Calculator',
    description: 'Calculate tips, split bills, and determine fair payment amounts.',
    path: '/tools/tip-calculator',
    category: 'calculator',
    keywords: ['tip', 'calculator', 'bill', 'split', 'payment', 'restaurant'],
    icon: '💸',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate Body Mass Index and get health recommendations.',
    path: '/tools/bmi-calculator',
    category: 'calculator',
    keywords: ['bmi', 'body mass index', 'health', 'weight', 'height', 'fitness'],
    icon: '⚖️',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate exact age, time between dates, and upcoming milestones.',
    path: '/tools/age-calculator',
    category: 'calculator',
    keywords: ['age', 'calculator', 'date', 'birthday', 'time', 'milestone'],
    icon: '🎂',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'pregnancy-calculator',
    name: 'Pregnancy Calculator',
    description: 'Calculate due dates, pregnancy weeks, and important milestones.',
    path: '/tools/pregnancy-calculator',
    category: 'calculator',
    keywords: ['pregnancy', 'due date', 'calculator', 'baby', 'gestation', 'weeks'],
    icon: '👶',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'calorie-calculator',
    name: 'Calorie Calculator',
    description: 'Calculate daily calorie needs, BMR, and macronutrient requirements.',
    path: '/tools/calorie-calculator',
    category: 'calculator',
    keywords: ['calorie', 'calculator', 'nutrition', 'diet', 'bmr', 'macros'],
    icon: '🍎',
    featured: false,
    priority: 0.6,
    built: false,
  },
  // ADVANCED ENCODING & CRYPTOGRAPHY
  {
    id: 'sha-generator',
    name: 'SHA Hash Generator',
    description: 'Generate SHA-1, SHA-256, SHA-512, and other SHA hash values.',
    path: '/tools/sha-generator',
    category: 'security',
    keywords: ['sha', 'hash', 'generate', 'sha1', 'sha256', 'sha512', 'cryptography'],
    icon: '🔐',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'bcrypt-generator',
    name: 'BCrypt Generator',
    description: 'Generate BCrypt hashes for secure password storage.',
    path: '/tools/bcrypt-generator',
    category: 'security',
    keywords: ['bcrypt', 'hash', 'password', 'security', 'encryption'],
    icon: '🔒',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'aes-encryptor',
    name: 'AES Encryptor/Decryptor',
    description: 'Encrypt and decrypt text using AES encryption algorithm.',
    path: '/tools/aes-encryptor',
    category: 'security',
    keywords: ['aes', 'encrypt', 'decrypt', 'cryptography', 'security', 'algorithm'],
    icon: '🔐',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'rsa-generator',
    name: 'RSA Key Generator',
    description: 'Generate RSA public and private key pairs for encryption.',
    path: '/tools/rsa-generator',
    category: 'security',
    keywords: ['rsa', 'key', 'generate', 'public', 'private', 'encryption'],
    icon: '🔑',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'rot13-encoder',
    name: 'ROT13 Encoder/Decoder',
    description: 'Simple Caesar cipher that rotates characters by 13 positions.',
    path: '/tools/rot13-encoder',
    category: 'encoding',
    keywords: ['rot13', 'caesar cipher', 'encode', 'decode', 'simple encryption'],
    icon: '🔄',
    featured: false,
    priority: 0.4,
    built: true,
  },
  {
    id: 'hex-encoder',
    name: 'Hex Encoder/Decoder',
    description: 'Convert text to hexadecimal and vice versa.',
    path: '/tools/hex-encoder',
    category: 'encoding',
    keywords: ['hex', 'hexadecimal', 'encode', 'decode', 'convert', 'binary'],
    icon: '🔢',
    featured: false,
    priority: 0.5,
    built: true,
  },
  {
    id: 'binary-encoder',
    name: 'Binary Encoder/Decoder',
    description: 'Convert text to binary and vice versa.',
    path: '/tools/binary-encoder',
    category: 'encoding',
    keywords: ['binary', 'encode', 'decode', 'convert', 'text', '0101'],
    icon: '💻',
    featured: false,
    priority: 0.5,
    built: true,
  },
  // ADVANCED TEXT & LANGUAGE TOOLS
  {
    id: 'text-analyzer',
    name: 'Text Analyzer',
    description: 'Analyze text for readability, sentiment, and linguistic features.',
    path: '/tools/text-analyzer',
    category: 'text',
    keywords: ['text', 'analyze', 'readability', 'sentiment', 'linguistics', 'analysis'],
    icon: '📊',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'language-detector',
    name: 'Language Detector',
    description: 'Detect the language of text using advanced algorithms.',
    path: '/tools/language-detector',
    category: 'text',
    keywords: ['language', 'detect', 'identify', 'text', 'multilingual'],
    icon: '🌍',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'text-summarizer',
    name: 'Text Summarizer',
    description: 'Generate concise summaries of long text content.',
    path: '/tools/text-summarizer',
    category: 'text',
    keywords: ['text', 'summarize', 'summary', 'extract', 'key points', 'condense'],
    icon: '📝',
    featured: false,
    priority: 0.7,
    built: false,
  },
  {
    id: 'plagiarism-checker',
    name: 'Plagiarism Checker',
    description: 'Check text for potential plagiarism and similarity.',
    path: '/tools/plagiarism-checker',
    category: 'text',
    keywords: ['plagiarism', 'check', 'similarity', 'duplicate', 'content', 'original'],
    icon: '🔍',
    featured: false,
    priority: 0.7,
    built: false,
  },
  {
    id: 'grammar-checker',
    name: 'Grammar Checker',
    description: 'Check and correct grammar, spelling, and punctuation errors.',
    path: '/tools/grammar-checker',
    category: 'text',
    keywords: ['grammar', 'check', 'spelling', 'punctuation', 'correct', 'writing'],
    icon: '✏️',
    featured: false,
    priority: 0.7,
    built: false,
  },
  {
    id: 'text-to-speech',
    name: 'Text to Speech',
    description: 'Convert text to speech with multiple voice options.',
    path: '/tools/text-to-speech',
    category: 'text',
    keywords: ['text to speech', 'tts', 'voice', 'audio', 'speak', 'convert'],
    icon: '🔊',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'speech-to-text',
    name: 'Speech to Text',
    description: 'Convert speech to text using voice recognition.',
    path: '/tools/speech-to-text',
    category: 'text',
    keywords: ['speech to text', 'voice recognition', 'transcribe', 'audio', 'convert'],
    icon: '🎤',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'acronym-generator',
    name: 'Acronym Generator',
    description: 'Generate acronyms and abbreviations from phrases.',
    path: '/tools/acronym-generator',
    category: 'text',
    keywords: ['acronym', 'generate', 'abbreviation', 'phrase', 'short form'],
    icon: '🔤',
    featured: false,
    priority: 0.4,
    built: false,
  },
  // ADVANCED WEB & NETWORK TOOLS
  {
    id: 'whois-lookup',
    name: 'WHOIS Lookup',
    description: 'Get detailed domain registration information and ownership details.',
    path: '/tools/whois-lookup',
    category: 'web',
    keywords: ['whois', 'domain', 'lookup', 'registration', 'owner', 'dns'],
    icon: '🔍',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'port-scanner',
    name: 'Port Scanner',
    description: 'Scan ports on a host to check for open services.',
    path: '/tools/port-scanner',
    category: 'web',
    keywords: ['port', 'scanner', 'network', 'security', 'services', 'open ports'],
    icon: '🔌',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'http-headers-checker',
    name: 'HTTP Headers Checker',
    description: 'Check HTTP headers and response information from websites.',
    path: '/tools/http-headers-checker',
    category: 'web',
    keywords: ['http', 'headers', 'check', 'response', 'server', 'web'],
    icon: '📋',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'redirect-checker',
    name: 'Redirect Checker',
    description: 'Check and analyze URL redirects and chains.',
    path: '/tools/redirect-checker',
    category: 'web',
    keywords: ['redirect', 'check', 'url', 'chain', '301', '302'],
    icon: '🔄',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'broken-link-checker',
    name: 'Broken Link Checker',
    description: 'Find broken links on websites and check link validity.',
    path: '/tools/broken-link-checker',
    category: 'web',
    keywords: ['broken link', 'check', '404', 'dead link', 'website', 'seo'],
    icon: '🔗',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'website-uptime-monitor',
    name: 'Website Uptime Monitor',
    description: 'Monitor website availability and response times.',
    path: '/tools/website-uptime-monitor',
    category: 'web',
    keywords: ['uptime', 'monitor', 'website', 'availability', 'response time'],
    icon: '📊',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'email-header-analyzer',
    name: 'Email Header Analyzer',
    description: 'Analyze email headers for routing and security information.',
    path: '/tools/email-header-analyzer',
    category: 'web',
    keywords: ['email', 'header', 'analyze', 'routing', 'security', 'spam'],
    icon: '📧',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'subdomain-enumerator',
    name: 'Subdomain Enumerator',
    description: 'Find subdomains of a domain using various techniques.',
    path: '/tools/subdomain-enumerator',
    category: 'web',
    keywords: ['subdomain', 'enumerate', 'find', 'domain', 'dns', 'security'],
    icon: '🔍',
    featured: false,
    priority: 0.5,
    built: false,
  },
  // ADVANCED IMAGE & MEDIA TOOLS
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images to specific dimensions while maintaining quality.',
    path: '/tools/image-resizer',
    category: 'image',
    keywords: ['image', 'resize', 'dimensions', 'pixels', 'quality', 'format'],
    icon: '🖼️',
    featured: false,
    priority: 0.7,
    built: false,
  },
  {
    id: 'image-converter',
    name: 'Image Format Converter',
    description: 'Convert images between different formats (JPG, PNG, GIF, WebP, etc.).',
    path: '/tools/image-converter',
    category: 'image',
    keywords: ['image', 'convert', 'format', 'jpg', 'png', 'gif', 'webp'],
    icon: '🔄',
    featured: false,
    priority: 0.7,
    built: false,
  },
  {
    id: 'image-watermarker',
    name: 'Image Watermarker',
    description: 'Add watermarks to images for branding and copyright protection.',
    path: '/tools/image-watermarker',
    category: 'image',
    keywords: ['image', 'watermark', 'branding', 'copyright', 'logo', 'text'],
    icon: '💧',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'image-cropper',
    name: 'Image Cropper',
    description: 'Crop images to remove unwanted areas and focus on specific content.',
    path: '/tools/image-cropper',
    category: 'image',
    keywords: ['image', 'crop', 'trim', 'cut', 'resize', 'focus'],
    icon: '✂️',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'image-filters',
    name: 'Image Filters',
    description: 'Apply various filters and effects to images.',
    path: '/tools/image-filters',
    category: 'image',
    keywords: ['image', 'filters', 'effects', 'edit', 'enhance', 'artistic'],
    icon: '🎨',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'screenshot-tool',
    name: 'Screenshot Tool',
    description: 'Take screenshots of web pages and capture screen content.',
    path: '/tools/screenshot-tool',
    category: 'image',
    keywords: ['screenshot', 'capture', 'screen', 'webpage', 'image'],
    icon: '📸',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'video-converter',
    name: 'Video Converter',
    description: 'Convert videos between different formats and resolutions.',
    path: '/tools/video-converter',
    category: 'media',
    keywords: ['video', 'convert', 'format', 'mp4', 'avi', 'mov', 'resolution'],
    icon: '🎬',
    featured: false,
    priority: 0.7,
    built: false,
  },
  {
    id: 'audio-converter',
    name: 'Audio Converter',
    description: 'Convert audio files between different formats (MP3, WAV, FLAC, etc.).',
    path: '/tools/audio-converter',
    category: 'media',
    keywords: ['audio', 'convert', 'mp3', 'wav', 'flac', 'format', 'music'],
    icon: '🎵',
    featured: false,
    priority: 0.6,
    built: false,
  },
  // ADVANCED DOCUMENT & FILE TOOLS
  {
    id: 'pdf-splitter',
    name: 'PDF Splitter',
    description: 'Split PDF files into multiple smaller documents.',
    path: '/tools/pdf-splitter',
    category: 'document',
    keywords: ['pdf', 'split', 'divide', 'pages', 'document', 'separate'],
    icon: '📄',
    featured: false,
    priority: 0.7,
    built: false,
  },
  {
    id: 'pdf-compressor',
    name: 'PDF Compressor',
    description: 'Reduce PDF file size while maintaining quality.',
    path: '/tools/pdf-compressor',
    category: 'document',
    keywords: ['pdf', 'compress', 'reduce', 'file size', 'optimize'],
    icon: '📄',
    featured: false,
    priority: 0.7,
    built: false,
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word Converter',
    description: 'Convert PDF documents to editable Word format.',
    path: '/tools/pdf-to-word',
    category: 'document',
    keywords: ['pdf', 'word', 'convert', 'docx', 'editable', 'document'],
    icon: '📝',
    featured: false,
    priority: 0.7,
    built: false,
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF Converter',
    description: 'Convert Word documents to PDF format.',
    path: '/tools/word-to-pdf',
    category: 'document',
    keywords: ['word', 'pdf', 'convert', 'docx', 'document'],
    icon: '📄',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF Converter',
    description: 'Convert Excel spreadsheets to PDF format.',
    path: '/tools/excel-to-pdf',
    category: 'document',
    keywords: ['excel', 'pdf', 'convert', 'spreadsheet', 'xlsx'],
    icon: '📊',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF Converter',
    description: 'Convert images to PDF documents.',
    path: '/tools/image-to-pdf',
    category: 'document',
    keywords: ['image', 'pdf', 'convert', 'document', 'photos'],
    icon: '🖼️',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'pdf-to-image',
    name: 'PDF to Image Converter',
    description: 'Convert PDF pages to image files.',
    path: '/tools/pdf-to-image',
    category: 'document',
    keywords: ['pdf', 'image', 'convert', 'pages', 'jpg', 'png'],
    icon: '🖼️',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'epub-converter',
    name: 'EPUB Converter',
    description: 'Convert documents to EPUB format for e-readers.',
    path: '/tools/epub-converter',
    category: 'document',
    keywords: ['epub', 'convert', 'ebook', 'reader', 'kindle', 'document'],
    icon: '📚',
    featured: false,
    priority: 0.5,
    built: false,
  },
  // ADVANCED DEVELOPER TOOLS
  {
    id: 'code-beautifier',
    name: 'Code Beautifier',
    description: 'Format and beautify code in various programming languages.',
    path: '/tools/code-beautifier',
    category: 'developer',
    keywords: ['code', 'beautify', 'format', 'indent', 'programming', 'syntax'],
    icon: '💻',
    featured: false,
    priority: 0.7,
    built: false,
  },
  {
    id: 'code-minifier',
    name: 'Code Minifier',
    description: 'Minify code to reduce file size and improve performance.',
    path: '/tools/code-minifier',
    category: 'developer',
    keywords: ['code', 'minify', 'compress', 'reduce', 'performance', 'size'],
    icon: '⚡',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'color-palette-generator',
    name: 'Color Palette Generator',
    description: 'Generate harmonious color palettes for design projects.',
    path: '/tools/color-palette-generator',
    category: 'design',
    keywords: ['color', 'palette', 'generate', 'harmonious', 'design', 'scheme'],
    icon: '🎨',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'gradient-generator',
    name: 'Gradient Generator',
    description: 'Create beautiful CSS gradients for web design.',
    path: '/tools/gradient-generator',
    category: 'design',
    keywords: ['gradient', 'css', 'generate', 'design', 'background', 'color'],
    icon: '🌈',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'box-shadow-generator',
    name: 'Box Shadow Generator',
    description: 'Generate CSS box shadows with visual preview.',
    path: '/tools/box-shadow-generator',
    category: 'design',
    keywords: ['box shadow', 'css', 'generate', 'design', 'shadow', 'effect'],
    icon: '🌫️',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'border-radius-generator',
    name: 'Border Radius Generator',
    description: 'Generate CSS border radius with visual preview.',
    path: '/tools/border-radius-generator',
    category: 'design',
    keywords: ['border radius', 'css', 'generate', 'rounded', 'corners'],
    icon: '🔲',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'font-pairing-generator',
    name: 'Font Pairing Generator',
    description: 'Generate harmonious font combinations for web design.',
    path: '/tools/font-pairing-generator',
    category: 'design',
    keywords: ['font', 'pairing', 'typography', 'combinations', 'design', 'web'],
    icon: '🔤',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'icon-generator',
    name: 'Icon Generator',
    description: 'Generate custom icons and favicons for websites.',
    path: '/tools/icon-generator',
    category: 'design',
    keywords: ['icon', 'generate', 'favicon', 'custom', 'website', 'design'],
    icon: '🎯',
    featured: false,
    priority: 0.5,
    built: false,
  },
  // GAMING & ENTERTAINMENT TOOLS
  {
    id: 'password-strength-checker',
    name: 'Password Strength Checker',
    description: 'Check the strength and security of passwords.',
    path: '/tools/password-strength-checker',
    category: 'security',
    keywords: ['password', 'strength', 'check', 'security', 'strong', 'weak'],
    icon: '🔒',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'random-name-generator',
    name: 'Random Name Generator',
    description: 'Generate random names for characters, projects, or businesses.',
    path: '/tools/random-name-generator',
    category: 'text',
    keywords: ['random', 'name', 'generate', 'character', 'project', 'business'],
    icon: '🎲',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'dice-roller',
    name: 'Dice Roller',
    description: 'Roll virtual dice for games and random number generation.',
    path: '/tools/dice-roller',
    category: 'calculator',
    keywords: ['dice', 'roll', 'random', 'game', 'number', 'generator'],
    icon: '🎲',
    featured: false,
    priority: 0.4,
    built: false,
  },
  {
    id: 'coin-flipper',
    name: 'Coin Flipper',
    description: 'Flip virtual coins for random heads or tails results.',
    path: '/tools/coin-flipper',
    category: 'calculator',
    keywords: ['coin', 'flip', 'heads', 'tails', 'random', 'decision'],
    icon: '🪙',
    featured: false,
    priority: 0.4,
    built: false,
  },
  {
    id: 'random-number-generator',
    name: 'Random Number Generator',
    description: 'Generate random numbers within specified ranges.',
    path: '/tools/random-number-generator',
    category: 'calculator',
    keywords: ['random', 'number', 'generate', 'range', 'lottery', 'selection'],
    icon: '🎲',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'decision-maker',
    name: 'Decision Maker',
    description: 'Make random decisions from a list of options.',
    path: '/tools/decision-maker',
    category: 'calculator',
    keywords: ['decision', 'maker', 'random', 'choice', 'options', 'select'],
    icon: '🎯',
    featured: false,
    priority: 0.4,
    built: false,
  },
  // BUSINESS & PRODUCTIVITY TOOLS
  {
    id: 'invoice-generator',
    name: 'Invoice Generator',
    description: 'Generate professional invoices for business transactions.',
    path: '/tools/invoice-generator',
    category: 'business',
    keywords: ['invoice', 'generate', 'business', 'billing', 'professional', 'payment'],
    icon: '📄',
    featured: false,
    priority: 0.7,
    built: false,
  },
  {
    id: 'receipt-generator',
    name: 'Receipt Generator',
    description: 'Generate receipts for purchases and transactions.',
    path: '/tools/receipt-generator',
    category: 'business',
    keywords: ['receipt', 'generate', 'purchase', 'transaction', 'proof', 'payment'],
    icon: '🧾',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'business-card-generator',
    name: 'Business Card Generator',
    description: 'Create professional business cards with custom designs.',
    path: '/tools/business-card-generator',
    category: 'business',
    keywords: ['business card', 'generate', 'professional', 'contact', 'design'],
    icon: '💼',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'qr-code-reader',
    name: 'QR Code Reader',
    description: 'Scan and decode QR codes from images.',
    path: '/tools/qr-code-reader',
    category: 'conversion',
    keywords: ['qr code', 'read', 'scan', 'decode', 'image', 'mobile'],
    icon: '📱',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'barcode-generator',
    name: 'Barcode Generator',
    description: 'Generate various types of barcodes for products and inventory.',
    path: '/tools/barcode-generator',
    category: 'conversion',
    keywords: ['barcode', 'generate', 'product', 'inventory', 'scan', 'code'],
    icon: '📊',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'barcode-reader',
    name: 'Barcode Reader',
    description: 'Scan and decode barcodes from images.',
    path: '/tools/barcode-reader',
    category: 'conversion',
    keywords: ['barcode', 'read', 'scan', 'decode', 'image', 'product'],
    icon: '📊',
    featured: false,
    priority: 0.5,
    built: false,
  },
  // DATA ANALYSIS & VISUALIZATION
  {
    id: 'data-visualizer',
    name: 'Data Visualizer',
    description: 'Create charts and graphs from data sets.',
    path: '/tools/data-visualizer',
    category: 'data',
    keywords: ['data', 'visualize', 'chart', 'graph', 'analysis', 'statistics'],
    icon: '📊',
    featured: false,
    priority: 0.7,
    built: false,
  },
  {
    id: 'statistics-calculator',
    name: 'Statistics Calculator',
    description: 'Calculate mean, median, mode, standard deviation, and other statistics.',
    path: '/tools/statistics-calculator',
    category: 'calculator',
    keywords: ['statistics', 'calculate', 'mean', 'median', 'mode', 'standard deviation'],
    icon: '📈',
    featured: false,
    priority: 0.6,
    built: false,
  },
  {
    id: 'sample-size-calculator',
    name: 'Sample Size Calculator',
    description: 'Calculate required sample sizes for statistical studies.',
    path: '/tools/sample-size-calculator',
    category: 'calculator',
    keywords: ['sample size', 'statistics', 'calculate', 'study', 'research', 'margin of error'],
    icon: '📊',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'correlation-calculator',
    name: 'Correlation Calculator',
    description: 'Calculate correlation coefficients between variables.',
    path: '/tools/correlation-calculator',
    category: 'calculator',
    keywords: ['correlation', 'calculate', 'coefficient', 'variables', 'statistics', 'relationship'],
    icon: '📈',
    featured: false,
    priority: 0.5,
    built: false,
  },
  // SPECIALIZED TOOLS
  {
    id: 'time-zone-converter',
    name: 'Time Zone Converter',
    description: 'Convert times between different time zones worldwide.',
    path: '/tools/time-zone-converter',
    category: 'conversion',
    keywords: ['time zone', 'convert', 'worldwide', 'schedule', 'meeting', 'travel'],
    icon: '🌍',
    featured: false,
    priority: 0.7,
    built: true,
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    description: 'Convert between different currencies with real-time exchange rates.',
    path: '/tools/currency-converter',
    category: 'conversion',
    keywords: ['currency', 'convert', 'exchange rate', 'money', 'forex', 'dollar'],
    icon: '💱',
    featured: true,
    priority: 0.8,
    built: false,
  },
  {
    id: 'temperature-converter',
    name: 'Temperature Converter',
    description: 'Convert between Celsius, Fahrenheit, and Kelvin temperature scales.',
    path: '/tools/temperature-converter',
    category: 'conversion',
    keywords: ['temperature', 'convert', 'celsius', 'fahrenheit', 'kelvin', 'weather'],
    icon: '🌡️',
    featured: false,
    priority: 0.6,
    built: true,
  },
  {
    id: 'length-converter',
    name: 'Length Converter',
    description: 'Convert between different units of length and distance.',
    path: '/tools/length-converter',
    category: 'conversion',
    keywords: ['length', 'convert', 'distance', 'meter', 'feet', 'inch', 'mile'],
    icon: '📏',
    featured: false,
    priority: 0.6,
    built: true,
  },
  {
    id: 'weight-converter',
    name: 'Weight Converter',
    description: 'Convert between different units of weight and mass.',
    path: '/tools/weight-converter',
    category: 'conversion',
    keywords: ['weight', 'convert', 'mass', 'pound', 'kilogram', 'ounce', 'gram'],
    icon: '⚖️',
    featured: false,
    priority: 0.6,
    built: true,
  },
  {
    id: 'area-converter',
    name: 'Area Converter',
    description: 'Convert between different units of area measurement.',
    path: '/tools/area-converter',
    category: 'conversion',
    keywords: ['area', 'convert', 'square', 'meter', 'feet', 'acre', 'hectare'],
    icon: '📐',
    featured: false,
    priority: 0.5,
    built: true,
  },
  {
    id: 'volume-converter',
    name: 'Volume Converter',
    description: 'Convert between different units of volume and capacity.',
    path: '/tools/volume-converter',
    category: 'conversion',
    keywords: ['volume', 'convert', 'liter', 'gallon', 'cubic', 'capacity'],
    icon: '🧪',
    featured: false,
    priority: 0.5,
    built: true,
  },
  {
    id: 'speed-converter',
    name: 'Speed Converter',
    description: 'Convert between different units of speed and velocity.',
    path: '/tools/speed-converter',
    category: 'conversion',
    keywords: ['speed', 'convert', 'mph', 'kmh', 'velocity', 'miles per hour'],
    icon: '🏃',
    featured: false,
    priority: 0.5,
    built: true,
  },
  {
    id: 'pressure-converter',
    name: 'Pressure Converter',
    description: 'Convert between different units of pressure measurement.',
    path: '/tools/pressure-converter',
    category: 'conversion',
    keywords: ['pressure', 'convert', 'psi', 'bar', 'pascal', 'atmosphere'],
    icon: '🌪️',
    featured: false,
    priority: 0.4,
    built: true,
  },
  {
    id: 'energy-converter',
    name: 'Energy Converter',
    description: 'Convert between different units of energy measurement.',
    path: '/tools/energy-converter',
    category: 'conversion',
    keywords: ['energy', 'convert', 'joule', 'calorie', 'btu', 'watt hour'],
    icon: '⚡',
    featured: false,
    priority: 0.4,
    built: true,
  },
  {
    id: 'power-converter',
    name: 'Power Converter',
    description: 'Convert between different units of power measurement.',
    path: '/tools/power-converter',
    category: 'conversion',
    keywords: ['power', 'convert', 'watt', 'horsepower', 'kilowatt', 'energy'],
    icon: '⚡',
    featured: false,
    priority: 0.4,
    built: true,
  },
  {
    id: 'data-storage-converter',
    name: 'Data Storage Converter',
    description: 'Convert between different units of digital data storage.',
    path: '/tools/data-storage-converter',
    category: 'conversion',
    keywords: ['data storage', 'convert', 'byte', 'kilobyte', 'megabyte', 'gigabyte'],
    icon: '💾',
    featured: false,
    priority: 0.5,
    built: false,
  },
  {
    id: 'digital-storage-converter',
    name: 'Digital Storage Converter',
    description: 'Convert between different digital storage units (bits, bytes, etc.).',
    path: '/tools/digital-storage-converter',
    category: 'conversion',
    keywords: ['digital storage', 'convert', 'bit', 'byte', 'nibble', 'word'],
    icon: '💾',
    featured: false,
    priority: 0.4,
    built: false,
  }
];

export const categories = [
  {
    id: 'encoding',
    name: 'Encoding & Decoding',
    description: 'Tools for encoding and decoding various formats',
  },
  {
    id: 'security',
    name: 'Security Tools',
    description: 'Tools for password generation and security',
  },
  {
    id: 'document',
    name: 'Document Tools',
    description: 'Tools for working with documents and files',
  },
  {
    id: 'developer',
    name: 'Developer Tools',
    description: 'Tools for developers and programmers',
  },
  {
    id: 'design',
    name: 'Design Tools',
    description: 'Tools for designers and creatives',
  },
  {
    id: 'image',
    name: 'Image Tools',
    description: 'Tools for image processing and manipulation',
  },
  {
    id: 'conversion',
    name: 'Conversion Tools',
    description: 'Tools for converting between different formats',
  },
  {
    id: 'text',
    name: 'Text Tools',
    description: 'Tools for text processing and manipulation',
  },
  {
    id: 'web',
    name: 'Web Tools',
    description: 'Tools for web development and analysis',
  },
  {
    id: 'file',
    name: 'File Tools',
    description: 'Tools for file management and processing',
  },
  {
    id: 'calculator',
    name: 'Calculator Tools',
    description: 'Various calculators and computational tools',
  },
  {
    id: 'media',
    name: 'Media Tools',
    description: 'Tools for audio and video processing',
  },
  {
    id: 'business',
    name: 'Business Tools',
    description: 'Tools for business and productivity',
  },
  {
    id: 'data',
    name: 'Data Analysis',
    description: 'Tools for data analysis and visualization',
  }
];

// Core utility functions
export function getToolById(id) {
  return tools.find(tool => tool.id === id);
}

export function getToolsByCategory(category) {
  return tools.filter(tool => tool.category === category);
}

export function getFeaturedTools() {
  return tools.filter(tool => tool.featured);
}

export function getRelatedTools(currentToolId, limit = 3) {
  const currentTool = getToolById(currentToolId);
  if (!currentTool) return [];
  
  return tools
    .filter(tool => tool.id !== currentToolId && tool.category === currentTool.category)
    .slice(0, limit);
}

export function getAllToolsForSitemap() {
  return tools.map(tool => ({
    url: `https://thetool.guru${tool.path}`,
    lastModified: new Date().toISOString(),
    changeFrequency: 'weekly',
    priority: tool.priority,
  }));
}

// Built vs unbuilt tools (driven by which routes are implemented)
export function getBuiltTools() {
  return tools.filter(tool => tool.built === true);
}

export function getUnbuiltTools() {
  return tools.filter(tool => tool.built !== true);
}

// Priority-based sorting and filtering
export function getToolsByPriority(limit = null) {
  const sortedTools = [...tools].sort((a, b) => (a.priority || 999) - (b.priority || 999));
  return limit ? sortedTools.slice(0, limit) : sortedTools;
}

export function getTopTools(count = 10) {
  return getToolsByPriority(count);
}

export function getMostPopularTools(count = 20) {
  return getToolsByPriority(count);
}

// Search functionality
export function searchTools(query) {
  const searchTerm = query.toLowerCase();
  return tools.filter(tool => 
    tool.name.toLowerCase().includes(searchTerm) ||
    tool.description.toLowerCase().includes(searchTerm) ||
    tool.keywords.some(keyword => keyword.toLowerCase().includes(searchTerm))
  );
}

// Status-based filtering
export function getToolsByStatus(status) {
  return tools.filter(tool => tool.status === status);
}

// Category statistics
export function getCategoryStats() {
  const stats = {};
  categories.forEach(category => {
    stats[category.id] = tools.filter(tool => tool.category === category.id).length;
  });
  return stats;
}

// Add new tools here - they will automatically be included in:
// - Sitemap generation
// - Navigation menus
// - Related tools suggestions
// - SEO metadata





